name: k_photo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  sensors_plus: ^3.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2  # Dependência para preferências locais
  lottie: ^2.2.0  # Dependência para animações Lottie
  sqflite: ^2.0.0+4  # Adicione esta linha (ou a versão mais recente disponível)
  path: ^1.8.0
  uuid: ^3.0.4  # Dependência para geração de UUID
  vector_math: ^2.1.1  # Dependência para transformações 3D
  image_picker: ^1.0.7  # Adicionado para seleção de imagens
  badges: ^3.1.2
  google_sign_in: ^6.1.0
  supabase_flutter: ^1.10.0
  gotrue: ^1.12.6
  postgrest: ^1.5.2
  timeago: ^3.7.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.11.0  # Pacote para adicionar ícones

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"  # Caminho para o ícone do app

flutter:
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

  assets:
    - assets/lombadabinder2.png
    - assets/capabinder2.png
    - assets/capas/binder1.png
    - assets/estante_infinita.png
    - assets/binder_back.png
    - assets/default_profile.png
    - assets/binder_background.png
    - assets/photocard1.png
    - assets/capas/capabinder1.png
    - assets/capas/capabinder2.png
    - assets/capas/capabinder3.png
    - assets/capas/capabinder4.png
    - assets/capas/lombadabinder1.png
    - assets/capas/lombadabinder2.png
    - assets/capas/lombadabinder3.png
    - assets/capas/lombadabinder4.png
    - assets/default_back.png
    - assets/photocard2.png
    - assets/photocard3.png  # Novo photocard
    - assets/photocard4.png  # Novo photocard
    #photocards
    - assets/photocards/
    - assets/plastic_texture.png
    - assets/app_icon.png  # Ícone do app
    - assets/your_animation_file.json  # Arquivo Lottie (substitua pelo nome do arquivo)
    - assets/default_profile.png
    - assets/frame/frame_1.png
    - assets/frame_none.png
    - assets/frame/frame_2.png
    - assets/frame/frame_3.png
    - assets/frame/frame_4.png
    - assets/frame/frame_5.png
    - assets/frame/frame_6.png
    - assets/kcoin.png     # Adicione esta linha
    - assets/starcoin.png

    - assets/google_logo.png
    - assets/keychain/keychain1.png
    - assets/keychain/keychain2.png
    - assets/keychain/keychain3.png
    - assets/stickers/
    - assets/stickers/